### ISSUE TITLE
Name collisions in properties doesn't generate a list type in string template.

### ISSUE THREAD

**Issue by xeranic** [kevinbirch/string-template-maven-plugin#6]
Hi Kevin,

I don't know if this considered a bug or not. In the usage page, it said: "N.B. The properties are installed into the template after the results of the controller, so if there are any name collisions then the value type will be automatically converted into a list type by StringTemplate."

But when I put two property with same name in the <properties> secion, only the last one's value showed. I think the "name collisions" in the document only means collision between controller and properties.

I saw we use Set to hold properties, may be change it to List could resolve the problem.

Regards

**Comment by kevinbirch** [comment]
Hi,

The nolo bene you mention refers to `<template>/<properties>`, which are passed to the StringTemplate renderer _after_ any the controller is run.  So, duplicates keys coming from `<template>/<properties>` and the controller's method cause StringTemplate to collect the values into a list.  This is just a quirk of StingTemplate that one should be aware of.  It is not a designed feature.

Putting two properties of the same name into the properties section does not have the same effect.  The type of the `<properties>` element is [`Map<String, String>`](https://github.com/kevinbirch/string-template-maven-plugin/blob/master/src/main/java/com/webguys/maven/plugin/st/Template.java#L80), so only the last key/value will be kept as you see.  Maven handles the conversion to the Map type, so there is no way to change this behavior.  The intention of the static properties in the POM file is for simple values, especially those are created using Maven property expansion.  Any rich value types (like List) should be created in a controller class.
